title: Andrew Eiring
Tech Support Pro | Operations Manager | Gastronomy Disciple
author: Andrew Eiring
email: andreweiring@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm a world traveler, technology geek, and I help companies provide world class customer support. 
  I like to use data to solve peoples problems and make enterprise partnerships profitable. 
  


# social links
github_username:  AndrewEiring

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
